### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by ProjectPete** [Azure/device-simulation-java#13] opened 2018-02-02 02:18 UTC
# Type of issue

- [ ] Bug
- [ ] New feature
- [x ] Improvement

# Description

The "Simulation service wiki" link on  is broken on a doc page.

# Steps to reproduce

1. Go to https://github.com/Azure/device-simulation-java
2. Scroll down to "Simulation service wiki" link, just before "Other Resources"

# Expected behavior

https://github.com/Azure/device-simulation-java/wiki

# Current behavior

https://github.com/Azure/device-simulation-java/blob/master/wiki/Device-Models

# Known workarounds

Click the wiki link at the top

**Comment by ppathan** [comment] 2018-02-03 00:57
Closing this a dupe of #11

**Closed by ppathan** 2018-02-03 00:57 UTC
